BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Admission] ADD [bedId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[Admission] ADD CONSTRAINT [Admission_bedId_fkey] FOREIGN KEY ([bedId]) REFERENCES [dbo].[Bed]([id]) ON DELETE SET NULL ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
